### ISSUE TITLE
Wifi Driver

### ISSUE THREAD

**Issue by M1cha** [MiCode/mi2_kernel#4]
The Wifi driver in this kernel is missing.
Since jb_2.5 this normally is located in drivers/staging/prima.

I think you compile it with a external repository in android. However I couldn't find a branch on caf which works with this kernel.

**Comment by PeterCxy** [comment]
You may ask huangqiwu.

**Comment by ivan19871002** [comment]
in vendor/qcom/prop  not in kernel source

**Comment by M1cha** [comment]
you mean this?
https://www.codeaurora.org/cgit/quic/la/platform/vendor/qcom-opensource/wlan/prima/
There isn't a branch for 4.1 And the newer driver isn't compatible(tons of compile errors)

**Comment by ivan19871002** [comment]
vendor/qcom/proprietary    not   vendor/qcom-opensource ,
Wifi driver is private on android .4.1 with caf codes

**Comment by M1cha** [comment]
https://www.codeaurora.org/cgit/quic/la/platform/vendor/qcom/proprietary ?
this redirects to:
https://www.codeaurora.org/cgit/quic/la/platform/vendor/qcom/proprietary-open/

and this doesn't contain the wifi driver.

**Comment by ivan19871002** [comment]
@MarkH-UK @M1cha https://github.com/mitwo-dev/mi2_kernel/tree/android-4.3

**Comment by redmaner** [comment]
The android 4.3 prima Wi-Fi driver is incompatible with android 4.1

**Comment by a375474942** [comment]
赞

**Comment by Furniel** [comment]
I managed to add qualcomm wi-fi driver to kernel and compile it, but kernel module doesnt load on MIUI because original miui module have two parameters, but qualcomm driver have only one(mac module_param is missing).
PS: No sound in headphones on miui with this sources and i don`t know why(problem with sources or i missed something in configuration).

**Comment by redmaner** [comment]
@Furniel
We have the same problem, working qcom driver but module is not working / loading because of missing mac.

Because Wi-Fi didn't worked I didn't check all functions. So don't know if this headphone playback issue is common. 

If it's a common issue it could be because Mi2 is using Dolby audio, which maybe isn't included in the sources (just widely guessing).

Anyway I hope that Xiaomi will release or point to the sources of the Wi-Fi driver so that we can actaully use these sources fully!

**Comment by M1cha** [comment]
I've just added this parameter but the driver still doesn't work then.
Many errors.

**Comment by M1cha** [comment]
The drivers was published on MiCode.
I've merged it into kernel source: https://github.com/M1cha/mi2_kernel/commits/A8064AAAAANLYA103051
